Nodejs week1 HW
Deepti-Dk/hyf-homework pull request #19
Opened 2020-08-30 17:17 UTC by Deepti-Dk

2020-09-05 16:01 UTC, kfazinic requested changes
Very nice job! 👏 

Have you tried running tests? One of them fails, try to fix it! 🙂

2020-09-07 09:40 UTC, Deepti-Dk commented on nodejs/week1/MealSharing/src/backend/app.js
> +});
Hey Kristine, I did npm install -D nodemon and npm install nodemon -g to sort meal.js and reservation.js to display different data on refresh but its still displaying same ones. Don't know what more I could do! Please advise:-)

2020-09-10 11:07 UTC, Deepti-Dk commented on nodejs/week1/MealSharing/src/backend/app.js
> +});
--Sorted--

2020-09-11 11:40 UTC, kfazinic approved these changes
👏

2020-09-11 12:08 UTC, merged