Nodejs/week3
Deepti-Dk/hyf-homework pull request #21
Opened 2020-09-10 20:06 UTC by Deepti-Dk

2020-09-13 15:50 UTC, Laila1222 requested changes
Hi Deepti :) 
It seems that you have pushed the node_modules file, as well as the whole week1 and week2 folders. I suppose there might have been something with creating new branches. Did you create a new branch from master when you created nodejs/week3? If not, that could be one explanation for the issue. 
I'm writing this, because in the 'Changed files' section, we only want to see the files that you actually worked with for this homework.  
Check out these answers for what to do: https://stackoverflow.com/questions/1139762/ignore-files-that-have-already-been-committed-to-a-git-repository 

Otherwise, very good job on your homework! 🥇

2020-09-13 15:50 UTC, Laila1222 commented on nodejs/week3/mealReservation/src/backend/api/meals.js
> +    } else if (request.query.availableReservations) {
Try: `availableReservations === 'true'` here

2020-09-13 18:28 UTC, Deepti-Dk commented
to be ignored as included all three branches HW for w1,w2,w3. will create a new PR just for w3

2020-09-13 18:42 UTC, Deepti-Dk commented
Re-opening!!!hopefully just with w3 HW

2020-09-14 18:25 UTC, Deepti-Dk commented
deleting it (will copy a new one)

2020-09-14 18:25 UTC, closed without merging